service: code-test-api

plugins:
  - serverless-esbuild
  - serverless-prune-plugin
  - serverless-offline

package:
  individually: true
  include:
    - 'node_modules/ajv-*/**'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

custom:
  esbuild:
    bundle: true
    minify: false
  prune:
    automatic: true
    number: 3
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 5001

functions:
  conditions:
    handler: src/handler.conditions
    events:
      - http:
          path: api
          method: get
          cors: true
